/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Ticket;

public class App {

    public static void main(String[] args) {
        Ticket t1;
        System.out.println("hello");
    }
}
